version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/gyuri/Docking/testing_stuff/plex/cfg:/config
      - /home/gyuri/Docking/testing_stuff/plex/tv:/tv
      - /home/gyuri/Docking/testing_stuff/plex/media:/movies
    restart: unless-stopped
